config/routes.rb
Rails.application.routes.draw do
  
  get 'cards/create'

  get 'cards/update'

  get 'cards/destroy'

  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'dashboard', to: 'static_pages#dashboard_view', view: 'day'
  get 'reload_container', to: 'static_pages#dashboard_reload'
  
  resources :rooms
  resources :clients

end

app/models/client.rb
class Client < ApplicationRecord

  has_many :cards, as: :cc_info

  scope :not_deleted, lambda { where(deleted_at: nil) }

  validates :first_name, :last_name, presence: true, length: {maximum: 128}, format: { with: /\A[A-Za-z -]+\z/, message: " not valid" }
  validates :phone_number, presence: true, uniqueness: { scope: :email }, length: {maximum: 20}, format: { with:/\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/, message: " not valid" }
  validates :email, presence: true, length: {maximum: 75}, format: { with:/\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, message: "not valid" }

  accepts_nested_attributes_for :cards


  private
    def destroy
      self.update_attributes(deleted_at: DateTime.current)
    end

    def delete
      destroy
    end
    
    def deleted?
      self.deleted_at.present?
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  
  def index
    @clients = Client.not_deleted.all
  end
  
  def show
    @client = Client.find(params[:id])
  end
  
  def new
    @client = Client.new
    @client.cards.build
  end
  
  def create
    @client = Client.new(client_params)
    if @client.save
      flash[:info] = "Client was successfuly added"
      redirect_to clients_url
    else
      render 'new'
    end
  end
  
  def edit
    @client = Client.find(params[:id])
  end
  
  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(client_params)
      flash[:success] = "Client was succesfully updated"
      redirect_to @client
    else
      render "edit.html.erb"
    end
  end

  def destroy
    @client = Client.find(params[:id]).destroy!
    flash[:success] = "Client was deleted"
    redirect_to clients_url
  end

  private
  
    def client_params
       params.require(:client).permit(:first_name, :last_name, :phone_number, :email, 
        cards_attributes: [:id, :card_name, :number, :card_type, :exp_month, :exp_year, :cvv])
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_client_form.html.erb
    <div class="form-container">
    <%= form_for(@client) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    
          <%= f.label :first_name, class: "control-label" %>
          <%= f.text_field :first_name, class: "form-control" %>
          <%= f.label :last_name, class: "control-label" %>
          <%= f.text_field :last_name, class: "form-control" %>
          <%= f.label :phone_number, class: "control-label" %>
          <%= f.text_field :phone_number, class: "form-control" %>
          <%= f.label :email, class: "control-label" %>
          <%= f.email_field :email, class: "form-control" %>
          <%= f.fields_for :cards do |f_card| %>
            <%= f.label :card_name, class: "control-label" %>
            <%= f_card.text_field :card_name, class: "form-control" %>
            <%= f.label :number, class: "control-label" %>
            <%= f_card.text_field :number, class: "form-control" %>
            <%= f.label :card_type, class: "control-label" %>
            <%= f_card.select(:card_type, ["Visa", "MasterCard"], {include_blank: true}, {class: "form-control"})  %>
            <%= f.label :exp_month, class: "control-label" %>
            <%= f_card.number_field :exp_month, class: "form-control" %>
            <%= f.label :exp_year, class: "control-label" %>
            <%= f_card.number_field :exp_year, class: "form-control" %>
            <%= f.label :cvv, class: "control-label" %>
            <%= f_card.text_field :cvv, class: "form-control" %>
          <% end %>
          <%= f.submit yield(:button_text), class: "btn btn-default" %>    
    <% end %>
    </div>

app/views/clients/edit.html.erb
<% provide(:button_text, "Update client") %>

<div class="page-header">
  <h1>Update client info</h1>
</div>

<div class="row">
  <div class="col-md-4  col-md-offset-2">
    
    <%= render "client_form" %>
    
  </div>
</div>

app/views/clients/index.html.erb
<div class="page-header">
  <h1>Clients List</h1>
  <%= link_to "Add new client", new_client_path, class: "btn btn-info" %>
  <!--search clients by name, phone number, email-->
</div>

 <table class="table">
    <thead>
      <tr>
        <th>Firstname</th>
        <th>Lastname</th>
        <th>Phone_number</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
    <% for client in @clients do %>
      <tr data-link="<%= client_path(client) %>" class="tr-link-style">
        <td><%= client.first_name %></td>
        <td><%= client.last_name %></td>
        <td><%= client.phone_number %></td>
        <td><%= client.email %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/clients/new.html.erb
<% provide(:button_text, "Add client") %>

<div class="page-header">
  <h1>Create new client</h1>
</div>

<div class="row">
  <div class="col-md-4  col-md-offset-2">
    <div class="form-container">
    <%= form_for(@client) do |f| %>
    
      <%= render "client_form" %>
    
    <% end %>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="list-group">
      <li class="list-group-item"><%= @client.first_name %></li>
      <li class="list-group-item"><%= @client.last_name %></li>
      <li class="list-group-item"><%= @client.phone_number %></li>
      <li class="list-group-item"><%= @client.email %></li>
    </ul>
    <%= link_to "Edit", edit_client_path(@client), class: "btn btn-default" %>
    <%= link_to "delete", @client, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default" %>
  </div>
</div>