config/routes.rb
Rails.application.routes.draw do
  
  get 'cards/create'

  get 'cards/update'

  get 'cards/destroy'

  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'dashboard', to: 'static_pages#dashboard_view', view: 'day'
  get 'reload_container', to: 'static_pages#dashboard_reload'
  
  resources :rooms
  resources :clients

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_bed_types, autosave: true, dependent: :destroy
  has_many :bed_types, through: :room_bed_types
  has_many :private_beds, dependent: :destroy
  
  accepts_nested_attributes_for :bed_types, reject_if: :all_blank
  accepts_nested_attributes_for :room_bed_types, reject_if: :all_blank, allow_destroy: true
  
  #had to include this method to make things work. there is a known issue that prevents 
  def bed_types_attributes=(attributes)
    attr_array = attributes.collect {|item| item[1][:id] }
    self.bed_type_ids = attr_array
    super
  end
  
  # callbacks
  before_update do
    adjust_private_beds if room_type_changed?
    adjust_private_beds if beds_changed?
  end
  
  PRIVACY_TYPE = ["private", "shared"]
  ROOM_SIZES = ['single', 'double','double-double', 'twin', 'triple', 'quadruple', 'family', 'studio']
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 8 }
  validates :pax, :max_pax, :beds, :bathrooms, numericality: { only_integer: true, less_than: 11, greater_than: 0 }
  validates :room_type, :bathroom_type, presence: true, inclusion: { in: PRIVACY_TYPE, message: "%{value} is not a valid privacy type" }
  validates :size, presence: true,  inclusion: { in: ROOM_SIZES, message: "%{value} is not a valid room size" }
  validates :floor, :extra_beds, numericality: { only_integer: true, allow_nil: true }
  
  # custom validations
  validate :max_capacity_cannot_be_less_than_capacity
  validate :bed_types_count_valid?, on: :create
  validate :room_bed_types_count_valid?, on: :update
  
  
  
  # cutom validation methods
  def max_capacity_cannot_be_less_than_capacity
    if pax && max_pax
      if max_pax < pax
        errors.add(:max_pax, "Maximum capacity cannot be less than capacity")
      end
    end
  end
  
  # custom methods
  
  # create private beds for shared room
  def create_private_beds
    self.beds.times do
      self.private_beds.create()
    end
  end

  private

    # adjust  private_beds for shared room if number of beds changed
    def adjust_private_beds
      if self.room_type == "shared"
        diff = self.beds - self.private_beds.count
          diff.abs.times {diff > 0 ? self.private_beds.create() : self.private_beds.destroy(self.private_beds.last)}
      else
        self.private_beds.clear # need to modify this behaviour later to check for assigned reservations for these private rooms
      end
    end
  
    # this method was not working properly, so I had to make to separate validations for create and update actions
    # def bed_types_count_valid?
    #   errors.add(:beds, "Wrong number of bed types#{bed_types.size}") unless room_bed_types.reject(&:marked_for_destruction?).size == beds || bed_types.size == beds
    # end
    # error explanation: on create action room_bed_types.reject(&:marked_for_destruction?).size was getting wrong values
    
    #create validation
    def bed_types_count_valid?
       errors.add(:base, "Wrong number of bed types#{bed_types.size}") unless bed_types.size == beds
    end
    
    #update validation
    def room_bed_types_count_valid?
       errors.add(:base, "Wrong number of bed types#{bed_types.size}") unless room_bed_types.reject(&:marked_for_destruction?).count == beds
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end
  
  def show
    @room = Room.find(params[:id])
  end

  def new
    @room = Room.new
    2.times {@room.bed_types.build}
  end
  
  #read comment_1 in Comments below
  def create
    @room = Room.new(room_params)
    if @room.save
      # && @room.bed_type_ids = params[:room][:bed_type_ids]
      @room.create_private_beds if @room.room_type == "shared"
      flash[:info] = "Room was successfuly created"
      redirect_to rooms_url
    else
      render 'new'
    end
  end
  
  def edit
    @room = Room.find(params[:id])
    @bed_types = @room.bed_types
  end
  
  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:success] = "Room updated"
      redirect_to @room
    else
      render 'edit'
    end
  end
  
  def destroy
    @room = Room.find(params[:id]).destroy
    flash[:success] = "Room deleted"
    redirect_to rooms_url
  end
  
  
  private
  
    def room_params
      params.require(:room).permit(:name, :size, :room_type, :pax, :max_pax, :beds, :extra_beds, :bathrooms, :bathroom_type, :floor, :description, 
      room_bed_types_attributes: [:id, :bed_type_id, :_destroy], 
      bed_types_attributes: [:id, :name, :width])
    end
  
    # def bed_type_params
    #   params.require(:bed_types).permit(options: params[:bed_types].keys) if params[:bed_types].any?
    # end


end


# Comments

# comment_1
# I create a room and associate bed types with it. 
# I wanted to do it the Rails way and create association automatically when Room is saved.
# I have almost managed to do it, when I reached an error. When getting bed_type_attributes, id, 
# it was trying to find an unexisting association of the unsaved room
# rails console output:
# params = {...}                                                                                                                                    
# => {:room=>{:name=>"110", :size=>"single", :room_type=>"private", :pax=>1, :max_pax=>1, 
# :beds=>1, :bathrooms=>1, :bathroom_type=>"private", :bed_types_attributes=>[{:id=>1}]}}
# rm = Room.create(params[:room])
# ActiveRecord::RecordNotFound: Couldn't find BedType with ID=1 for Room with ID=
# I had to rewrite one method to go around this error

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_bed_type_edit.html.erb
<div class="room-list-item">  
  <div class="bed-type-select-container">
    <%= f.fields_for :room_bed_types do |f_bed_type| %>
      <div class="bed-type-field-container">
        <%= f_bed_type.collection_select(:bed_type_id, BedType.all, :id, :name, { include_blank: true }) %>
        <%= f_bed_type.check_box :_destroy %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/_bed_type_new.html.erb
<div class="room-list-item">  
  <div class="bed-type-select-container">
    <% @room.bed_types.each do |bed_type| %>
    <%= f.fields_for :bed_types, bed_type do |f_bed_type| %>
      <div class="bed-type-field-container">
      <%= f_bed_type.collection_select(:id, BedType.all, :id, :name, { include_blank: true }) %>
      </div>
    <% end %>
    <% end %>
  </div>
</div>

app/views/rooms/_room.html.erb
<div class="rooms-item">
  <ul class="list-group">
    <li class="list-group-item"><%= room.name %> - a <strong><%= room.room_type %> <%= room.size %></strong> room</li>
    <li class="list-group-item">with <strong><%= room.bathrooms %> <%= room.bathroom_type %></strong> bathroom and <strong><%= room.beds %></strong> bed</li>
    <li class="list-group-item">Capacity(Max): <strong><%= room.pax %> (<%= room.max_pax %>)</strong></li>
    <%= link_to "edit", edit_room_path(room) %> |
    <%= link_to "delete", room, method: :delete, data: { confirm: "You sure?" } %>
  </ul>
</div>

app/views/rooms/_room_form.html.erb
<%= form_for(@room) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>


    <%= render "room_list_menu" %>
    
    <div class="room-list-row">
      <%= f.text_field :name, class: 'room-list-item' %>
      <%= f.select(:size, ['single', 'double','double-double', 'twin', 'triple', 'quadruple', 'family', 'studio'], {include_blank: ""}, { :class => 'room-list-item' }) %>
      <%= f.select(:room_type, ['private', 'shared'], {include_blank: ""}, { :class => 'room-list-item' }) %>
      <%= f.number_field :bathrooms, class: 'room-list-item' %>
      <%= f.select(:bathroom_type, ['private', 'shared'], {include_blank: ""}, { :class => 'room-list-item' }) %>
      <%= f.number_field :pax, class: 'room-list-item' %>
      <%= f.number_field :max_pax, class: 'room-list-item' %>
      <%= f.number_field :beds, class: 'room-list-item' %>
      <%= f.number_field :extra_beds, class: 'room-list-item' %>
      <%= f.number_field :floor, class: 'room-list-item' %>
      <%= f.text_field :description, class: 'room-list-item' %>
      <%= f.submit yield(:button_text), class: "room-list-item" %>

      <%= render partial: "bed_type_#{action}", locals: {f: f} %>

    </div>

<% end %>
        

app/views/rooms/_room_list.html.erb
<div class="room-list-row">
  <div class="room-list-item">
    <div><%= room.name %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.size %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.room_type %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.bathrooms %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.bathroom_type %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.pax %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.max_pax %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.beds %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.extra_beds %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.floor %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.description %></div>
  </div>
  <div class="room-list-item">
    <div><%= room.created_at %></div>
  </div>
</div>

app/views/rooms/_room_list_menu.html.erb
<div class="room-list-menu room-list-row">
  <div class="room-list-item">
    <div>Number</div>
  </div>
  <div class="room-list-item">
    <div>Size</div>
  </div>
  <div class="room-list-item">
    <div>Room type</div>
  </div>
  <div class="room-list-item">
    <div>Bathrooms</div>
  </div>
  <div class="room-list-item">
    <div>Bathroom type</div>
  </div>
  <div class="room-list-item">
    <div>Capacity</div>
  </div>
  <div class="room-list-item">
    <div>Capacity (max)</div>
  </div>
  <div class="room-list-item">
    <div>Number of beds</div>
  </div>
  <div class="room-list-item">
    <div>Extra beds?</div>
  </div>
  <div class="room-list-item">
    <div>Floor</div>
  </div>
  <div class="room-list-item">
    <div>Description</div>
  </div>
  <div class="room-list-item">
    <div>Created At</div>
  </div>
</div>

app/views/rooms/edit.html.erb
<% provide(:button_text, 'Save changes') %>

  <div class=page-header>
    <h1>Edit room</h1>
  </div>

  <div class="new-room-container">
  
  <%= render partial: "room_form", locals: {action: "edit"} %>
  
  </div>

app/views/rooms/index.html.erb
<% provide(:title, "Rooms") %>


  <div class=page-header>
    <h1>Rooms collection</h1>
  </div>
  <div class="rooms-container">
    <%= render @rooms %>
  </div>
  
  <h1> Rooms list </h1>
  <div class="rooms-list-container">
    <%= render "room_list_menu" %>
    
    <% @rooms.each do |room| %>
      <%= render partial: "room_list", locals: {room: room} %>
    <% end %>

    
  </div>

app/views/rooms/new.html.erb
<% provide(:button_text, 'Create room') %>

  <div class=page-header>
    <h1>Create new room</h1>
  </div>

  <div class="new-room-container">
  
  <%= render partial: "room_form", locals: {action: "new"} %>
  
  </div>