config/routes.rb
Rails.application.routes.draw do
  
  get 'cards/create'

  get 'cards/update'

  get 'cards/destroy'

  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  get 'dashboard', to: 'static_pages#dashboard_view', view: 'day'
  get 'reload_container', to: 'static_pages#dashboard_reload'
  
  resources :rooms
  resources :clients

end

app/views/layouts/_flash_messages.html.erb
      <div class="flash-container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-dismissible alert-<%= message_type %>">
          <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
          <%= message %>
        </div>
          <% end %>
      </div>

app/views/layouts/_header.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><%= link_to "Dashboard", dashboard_path %></li>
            <li><%= link_to "Rooms", rooms_path %></li>
            <li><%= link_to "Clients", clients_path %></li>
          </ul>
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags !-->
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">   <!-- Icons !-->
  
  
</head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/flash_messages" %>

      <%= yield %>
    
    </div>
    
    <div class="debug">
      <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>